# Use the official .NET Core SDK image as a base
FROM mcr.microsoft.com/dotnet/sdk:8.0.204 AS build-env

# Set the working directory in the container
WORKDIR /app

# Copy the .csproj file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the entire project and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0.204
WORKDIR /app
COPY --from=build-env /app/out .
EXPOSE 80

# Command to run the .NET Core app
ENTRYPOINT ["dotnet", "API.dll"]